apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: be-pipeline-listener-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - kind: TriggerBinding
        ref: be-pipeline-binding-dev
      interceptors:
        - cel:
            filter: (body.ref.startsWith('refs/heads/dev'))
      template:
        name: be-pipeline-template-dev

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: be-pipeline-binding-dev
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: be-pipeline-template-dev
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: app-be-pipeline-dev-run-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: be-pipeline-dev
        resources:
          - name: app-be-git-repo
            resourceRef:
              name: app-be-git-repo
          - name: app-be-image-dev
            resourceRef:
              name: app-be-image-dev
        params:
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/app-be-dev/app-be:dev'
          - name: GIT_REPO
            value: 'https://github.com/makentenza/sap-side-by-side-be.git'
          - name: GIT_REVISION
            value: dev
          - name: DC_NAME
            value: app-be
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: gitdir-dev

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: be-pipeline-webhook-dev
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-be-pipeline-listener-dev
    weight: 100
