apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-be-git-repo
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/makentenza/sap-side-by-side-be.git'
    - name: GIT_REVISION
      value: dev
  type: git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-be-image-dev
spec:
  type: image
  params:
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/app-be-dev/app-be:dev

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-be-image-qa
spec:
  type: image
  params:
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/app-be-qa/app-be:qa