apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limitrange
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-limitrange-mem-limit-range
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["app-*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: compute-resources
                spec:
                  hard:
                    pods: "4" 
                    requests.cpu: "1" 
                    requests.memory: 1Gi 
                    requests.ephemeral-storage: 2Gi 
                    limits.cpu: "2" 
                    limits.memory: 2Gi 
                    limits.ephemeral-storage: 4Gi
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitrange
  namespace: default
placementRef:
  name: placement-policy-limitrange
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-limitrange
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-limitrange
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: app-be, operator: In, values: ["true"]}
      - {key: app-fe, operator: In, values: ["true"]}
