apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: fe-pipeline-listener-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - kind: TriggerBinding
        ref: fe-pipeline-binding-dev
      interceptors:
        - cel:
            filter: (body.ref.startsWith('refs/heads/dev'))
      template:
        ref: fe-pipeline-template-dev

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: fe-pipeline-binding-dev
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: fe-pipeline-template-dev
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: app-fe-pipeline-dev-run-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: fe-pipeline-dev
        resources:
          - name: app-fe-git-repo
            resourceRef:
              name: app-fe-git-repo
          - name: app-fe-image-dev
            resourceRef:
              name: app-fe-image-dev
        params:
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/app-fe-dev/app-fe:dev'
          - name: GIT_REPO
            value: 'https://github.com/redhat-sap/sap-side-by-side-fe.git'
          - name: GIT_REVISION
            value: dev
          - name: DC_NAME
            value: app-fe
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: gitdir-dev

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fe-pipeline-webhook-dev
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-fe-pipeline-listener-dev
    weight: 100
