apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-fe-qa
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-fe-qa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-fe-qa
    repoURL: https://github.com/makentenza/sap-side-by-side-ci.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}